package il.co.tmg.dependencychecker

class Main {
}
/*

LIST OF DEPENDENCIES


Task :app:androidDependencies
debug
debugCompileClasspath - Dependencies for compilation
+--- ch.acra:acra-core:5.11.2@aar
+--- com.google.android.material:material:1.11.0@aar
+--- androidx.appcompat:appcompat:1.6.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.activity:activity:1.8.0@aar
+--- androidx.work:work-runtime-ktx:2.7.1@aar
+--- androidx.work:work-runtime:2.7.1@aar
+--- androidx.dynamicanimation:dynamicanimation:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.lifecycle:lifecycle-livedata-core:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2@aar
+--- androidx.core:core-ktx:1.12.0@aar
+--- androidx.appcompat:appcompat-resources:1.6.1@aar
+--- androidx.drawerlayout:drawerlayout:1.1.1@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.customview:customview:1.1.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.6.2@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.6.2@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10@jar
+--- com.google.auto.service:auto-service-annotations:1.1.1@jar
+--- androidx.constraintlayout:constraintlayout:2.1.4@aar
+--- org.slf4j:slf4j-api:2.0.9@jar
+--- com.github.tony19:logback-android:3.0.0@aar
+--- net.lingala.zip4j:zip4j:2.11.5@jar
+--- org.pgpainless:pgpainless-sop:1.6.2@jar
+--- com.google.code.gson:gson:2.10.1@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10@jar
+--- androidx.savedstate:savedstate:1.2.1@aar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.cardview:cardview:1.0.0@aar
+--- androidx.versionedparcelable:versionedparcelable:1.1.1@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-common:2.2.0@jar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- androidx.startup:startup-runtime:1.1.1@aar
+--- androidx.resourceinspection:resourceinspection-annotation:1.0.1@jar
\--- org.pgpainless:sop-java:7.0.0@jar

debugRuntimeClasspath - Dependencies for runtime/packaging
+--- ch.acra:acra-core:5.11.2@aar
+--- com.google.android.material:material:1.11.0@aar
+--- androidx.constraintlayout:constraintlayout:2.1.4@aar
+--- androidx.appcompat:appcompat-resources:1.6.1@aar
+--- androidx.appcompat:appcompat:1.6.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.activity:activity:1.8.0@aar
+--- androidx.emoji2:emoji2-views-helper:1.2.0@aar
+--- androidx.emoji2:emoji2:1.2.0@aar
+--- androidx.savedstate:savedstate:1.2.1@aar
+--- androidx.work:work-runtime-ktx:2.7.1@aar
+--- androidx.work:work-runtime:2.7.1@aar
+--- androidx.dynamicanimation:dynamicanimation:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.lifecycle:lifecycle-service:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.lifecycle:lifecycle-livedata-core:2.6.2@aar
+--- androidx.lifecycle:lifecycle-process:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2@aar
+--- androidx.core:core-ktx:1.12.0@aar
+--- androidx.drawerlayout:drawerlayout:1.1.1@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.customview:customview:1.1.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.6.2@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.6.2@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10@jar
+--- org.pgpainless:pgpainless-sop:1.6.2@jar
+--- org.pgpainless:pgpainless-core:1.6.2@jar
+--- org.slf4j:slf4j-api:2.0.9@jar
+--- com.github.tony19:logback-android:3.0.0@aar
+--- net.lingala.zip4j:zip4j:2.11.5@jar
+--- com.google.code.gson:gson:2.10.1@jar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.resourceinspection:resourceinspection-annotation:1.0.1@jar
+--- androidx.cardview:cardview:1.0.0@aar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.versionedparcelable:versionedparcelable:1.1.1@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.room:room-runtime:2.2.5@aar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-common:2.2.0@jar
+--- androidx.profileinstaller:profileinstaller:1.3.0@aar
+--- androidx.startup:startup-runtime:1.1.1@aar
+--- androidx.tracing:tracing:1.0.0@aar
+--- androidx.sqlite:sqlite-framework:2.1.0@aar
+--- androidx.sqlite:sqlite:2.1.0@aar
+--- androidx.concurrent:concurrent-futures:1.1.0@jar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.room:room-common:2.2.5@jar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- com.google.auto.service:auto-service:1.1.1@jar
+--- com.google.auto:auto-common:1.2.1@jar
+--- com.google.guava:guava:32.0.1-jre@jar
+--- com.google.errorprone:error_prone_annotations:2.18.0@jar
+--- androidx.constraintlayout:constraintlayout-core:1.0.4@jar
+--- org.pgpainless:sop-java:7.0.0@jar
+--- com.google.code.findbugs:jsr305:3.0.2@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.auto.service:auto-service-annotations:1.1.1@jar
+--- org.bouncycastle:bcpg-jdk18on:1.76@jar
+--- org.bouncycastle:bcprov-jdk18on:1.76@jar
+--- com.google.guava:failureaccess:1.0.1@jar
+--- org.checkerframework:checker-qual:3.33.0@jar
\--- com.google.j2objc:j2objc-annotations:2.8@jar

release
releaseCompileClasspath - Dependencies for compilation
+--- ch.acra:acra-core:5.11.2@aar
+--- com.google.android.material:material:1.11.0@aar
+--- androidx.appcompat:appcompat:1.6.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.activity:activity:1.8.0@aar
+--- androidx.work:work-runtime-ktx:2.7.1@aar
+--- androidx.work:work-runtime:2.7.1@aar
+--- androidx.dynamicanimation:dynamicanimation:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.lifecycle:lifecycle-livedata-core:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2@aar
+--- androidx.core:core-ktx:1.12.0@aar
+--- androidx.appcompat:appcompat-resources:1.6.1@aar
+--- androidx.drawerlayout:drawerlayout:1.1.1@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.customview:customview:1.1.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.6.2@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.6.2@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10@jar
+--- com.google.auto.service:auto-service-annotations:1.1.1@jar
+--- androidx.constraintlayout:constraintlayout:2.1.4@aar
+--- org.slf4j:slf4j-api:2.0.9@jar
+--- com.github.tony19:logback-android:3.0.0@aar
+--- net.lingala.zip4j:zip4j:2.11.5@jar
+--- org.pgpainless:pgpainless-sop:1.6.2@jar
+--- com.google.code.gson:gson:2.10.1@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10@jar
+--- androidx.savedstate:savedstate:1.2.1@aar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.cardview:cardview:1.0.0@aar
+--- androidx.versionedparcelable:versionedparcelable:1.1.1@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-common:2.2.0@jar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- androidx.startup:startup-runtime:1.1.1@aar
+--- androidx.resourceinspection:resourceinspection-annotation:1.0.1@jar
\--- org.pgpainless:sop-java:7.0.0@jar

releaseRuntimeClasspath - Dependencies for runtime/packaging
+--- ch.acra:acra-core:5.11.2@aar
+--- com.google.android.material:material:1.11.0@aar
+--- androidx.constraintlayout:constraintlayout:2.1.4@aar
+--- androidx.appcompat:appcompat-resources:1.6.1@aar
+--- androidx.appcompat:appcompat:1.6.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.activity:activity:1.8.0@aar
+--- androidx.emoji2:emoji2-views-helper:1.2.0@aar
+--- androidx.emoji2:emoji2:1.2.0@aar
+--- androidx.savedstate:savedstate:1.2.1@aar
+--- androidx.work:work-runtime-ktx:2.7.1@aar
+--- androidx.work:work-runtime:2.7.1@aar
+--- androidx.dynamicanimation:dynamicanimation:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.lifecycle:lifecycle-service:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.lifecycle:lifecycle-livedata-core:2.6.2@aar
+--- androidx.lifecycle:lifecycle-process:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2@aar
+--- androidx.core:core-ktx:1.12.0@aar
+--- androidx.drawerlayout:drawerlayout:1.1.1@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.customview:customview:1.1.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.6.2@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.6.2@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10@jar
+--- org.pgpainless:pgpainless-sop:1.6.2@jar
+--- org.pgpainless:pgpainless-core:1.6.2@jar
+--- org.slf4j:slf4j-api:2.0.9@jar
+--- com.github.tony19:logback-android:3.0.0@aar
+--- net.lingala.zip4j:zip4j:2.11.5@jar
+--- com.google.code.gson:gson:2.10.1@jar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.resourceinspection:resourceinspection-annotation:1.0.1@jar
+--- androidx.cardview:cardview:1.0.0@aar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.versionedparcelable:versionedparcelable:1.1.1@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.room:room-runtime:2.2.5@aar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-common:2.2.0@jar
+--- androidx.profileinstaller:profileinstaller:1.3.0@aar
+--- androidx.startup:startup-runtime:1.1.1@aar
+--- androidx.tracing:tracing:1.0.0@aar
+--- androidx.sqlite:sqlite-framework:2.1.0@aar
+--- androidx.sqlite:sqlite:2.1.0@aar
+--- androidx.concurrent:concurrent-futures:1.1.0@jar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.room:room-common:2.2.5@jar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- com.google.auto.service:auto-service:1.1.1@jar
+--- com.google.auto:auto-common:1.2.1@jar
+--- com.google.guava:guava:32.0.1-jre@jar
+--- com.google.errorprone:error_prone_annotations:2.18.0@jar
+--- androidx.constraintlayout:constraintlayout-core:1.0.4@jar
+--- org.pgpainless:sop-java:7.0.0@jar
+--- com.google.code.findbugs:jsr305:3.0.2@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.auto.service:auto-service-annotations:1.1.1@jar
+--- org.bouncycastle:bcpg-jdk18on:1.76@jar
+--- org.bouncycastle:bcprov-jdk18on:1.76@jar
+--- com.google.guava:failureaccess:1.0.1@jar
+--- org.checkerframework:checker-qual:3.33.0@jar
\--- com.google.j2objc:j2objc-annotations:2.8@jar

debugAndroidTest
debugAndroidTestCompileClasspath - Dependencies for compilation
+--- :app (variant: debug)
+--- androidx.test.ext:junit:1.1.5@aar
+--- androidx.test.espresso:espresso-core:3.5.1@aar
+--- ch.acra:acra-core:5.11.2@aar
+--- com.google.android.material:material:1.11.0@aar
+--- androidx.appcompat:appcompat:1.6.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.activity:activity:1.8.0@aar
+--- androidx.test:core:1.5.0@aar
+--- androidx.dynamicanimation:dynamicanimation:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.work:work-runtime-ktx:2.7.1@aar
+--- androidx.work:work-runtime:2.7.1@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata-core:2.6.2@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2@aar
+--- androidx.core:core-ktx:1.12.0@aar
+--- androidx.appcompat:appcompat-resources:1.6.1@aar
+--- androidx.drawerlayout:drawerlayout:1.1.1@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.customview:customview:1.1.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.6.2@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.6.2@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10@jar
+--- androidx.constraintlayout:constraintlayout:2.1.4@aar
+--- org.slf4j:slf4j-api:2.0.9@jar
+--- com.github.tony19:logback-android:3.0.0@aar
+--- net.lingala.zip4j:zip4j:2.11.5@jar
+--- org.pgpainless:pgpainless-sop:1.6.2@jar
+--- com.google.code.gson:gson:2.10.1@jar
+--- androidx.test:runner:1.5.2@aar
+--- junit:junit:4.13.2@jar
+--- org.hamcrest:hamcrest-integration:1.3@jar
+--- org.hamcrest:hamcrest-library:1.3@jar
+--- org.hamcrest:hamcrest-core:1.3@jar
+--- androidx.test.services:storage:1.4.2@aar
+--- androidx.test:monitor:1.6.1@aar
+--- androidx.test:annotation:1.0.1@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.cardview:cardview:1.0.0@aar
+--- androidx.concurrent:concurrent-futures:1.1.0@jar
+--- androidx.versionedparcelable:versionedparcelable:1.1.1@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.arch.core:core-runtime:2.1.0@aar
+--- androidx.arch.core:core-common:2.2.0@jar
+--- androidx.savedstate:savedstate:1.2.1@aar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- org.jetbrains:annotations:13.0@jar
+--- androidx.tracing:tracing:1.0.0@aar
+--- com.google.code.findbugs:jsr305:3.0.2@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- androidx.test.espresso:espresso-idling-resource:3.5.1@aar
+--- com.squareup:javawriter:2.1.1@jar
+--- javax.inject:javax.inject:1@jar
+--- androidx.resourceinspection:resourceinspection-annotation:1.0.1@jar
+--- org.pgpainless:sop-java:7.0.0@jar
\--- androidx.startup:startup-runtime:1.0.0@aar

debugAndroidTestRuntimeClasspath - Dependencies for runtime/packaging
+--- androidx.test.ext:junit:1.1.5@aar
+--- androidx.test.espresso:espresso-core:3.5.1@aar
+--- androidx.test:core:1.5.0@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.test:runner:1.5.2@aar
+--- androidx.test.services:storage:1.4.2@aar
+--- androidx.test:monitor:1.6.1@aar
+--- androidx.test:annotation:1.0.1@aar
+--- androidx.tracing:tracing:1.0.0@aar
+--- androidx.concurrent:concurrent-futures:1.1.0@jar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- com.google.code.findbugs:jsr305:3.0.2@jar
+--- junit:junit:4.13.2@jar
+--- androidx.test.espresso:espresso-idling-resource:3.5.1@aar
+--- com.squareup:javawriter:2.1.1@jar
+--- javax.inject:javax.inject:1@jar
+--- org.hamcrest:hamcrest-integration:1.3@jar
+--- org.hamcrest:hamcrest-library:1.3@jar
\--- org.hamcrest:hamcrest-core:1.3@jar

debugUnitTest
debugUnitTestCompileClasspath - Dependencies for compilation
+--- :app (variant: debug)
+--- ch.acra:acra-core:5.11.2@aar
+--- com.google.android.material:material:1.11.0@aar
+--- androidx.appcompat:appcompat:1.6.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.activity:activity:1.8.0@aar
+--- androidx.work:work-runtime-ktx:2.7.1@aar
+--- androidx.work:work-runtime:2.7.1@aar
+--- androidx.dynamicanimation:dynamicanimation:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.lifecycle:lifecycle-livedata-core:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2@aar
+--- androidx.core:core-ktx:1.12.0@aar
+--- androidx.appcompat:appcompat-resources:1.6.1@aar
+--- androidx.drawerlayout:drawerlayout:1.1.1@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.customview:customview:1.1.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.6.2@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.6.2@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10@jar
+--- androidx.constraintlayout:constraintlayout:2.1.4@aar
+--- org.slf4j:slf4j-api:2.0.9@jar
+--- com.github.tony19:logback-android:3.0.0@aar
+--- net.lingala.zip4j:zip4j:2.11.5@jar
+--- org.pgpainless:pgpainless-sop:1.6.2@jar
+--- com.google.code.gson:gson:2.10.1@jar
+--- junit:junit:4.13.2@jar
+--- org.hamcrest:hamcrest-core:1.3@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10@jar
+--- androidx.savedstate:savedstate:1.2.1@aar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.cardview:cardview:1.0.0@aar
+--- androidx.versionedparcelable:versionedparcelable:1.1.1@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-common:2.2.0@jar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- androidx.startup:startup-runtime:1.1.1@aar
+--- androidx.resourceinspection:resourceinspection-annotation:1.0.1@jar
\--- org.pgpainless:sop-java:7.0.0@jar

debugUnitTestRuntimeClasspath - Dependencies for runtime/packaging
+--- junit:junit:4.13.2@jar
+--- ch.acra:acra-core:5.11.2@aar
+--- com.google.android.material:material:1.11.0@aar
+--- androidx.constraintlayout:constraintlayout:2.1.4@aar
+--- androidx.appcompat:appcompat-resources:1.6.1@aar
+--- androidx.appcompat:appcompat:1.6.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.activity:activity:1.8.0@aar
+--- androidx.emoji2:emoji2-views-helper:1.2.0@aar
+--- androidx.emoji2:emoji2:1.2.0@aar
+--- androidx.savedstate:savedstate:1.2.1@aar
+--- androidx.work:work-runtime-ktx:2.7.1@aar
+--- androidx.work:work-runtime:2.7.1@aar
+--- androidx.dynamicanimation:dynamicanimation:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.lifecycle:lifecycle-service:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.lifecycle:lifecycle-livedata-core:2.6.2@aar
+--- androidx.lifecycle:lifecycle-process:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2@aar
+--- androidx.core:core-ktx:1.12.0@aar
+--- androidx.drawerlayout:drawerlayout:1.1.1@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.customview:customview:1.1.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.6.2@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.6.2@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10@jar
+--- org.pgpainless:pgpainless-sop:1.6.2@jar
+--- org.pgpainless:pgpainless-core:1.6.2@jar
+--- org.slf4j:slf4j-api:2.0.9@jar
+--- com.github.tony19:logback-android:3.0.0@aar
+--- net.lingala.zip4j:zip4j:2.11.5@jar
+--- com.google.code.gson:gson:2.10.1@jar
+--- org.hamcrest:hamcrest-core:1.3@jar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.resourceinspection:resourceinspection-annotation:1.0.1@jar
+--- androidx.cardview:cardview:1.0.0@aar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.versionedparcelable:versionedparcelable:1.1.1@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.room:room-runtime:2.2.5@aar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-common:2.2.0@jar
+--- androidx.profileinstaller:profileinstaller:1.3.0@aar
+--- androidx.startup:startup-runtime:1.1.1@aar
+--- androidx.tracing:tracing:1.0.0@aar
+--- androidx.sqlite:sqlite-framework:2.1.0@aar
+--- androidx.sqlite:sqlite:2.1.0@aar
+--- androidx.concurrent:concurrent-futures:1.1.0@jar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.room:room-common:2.2.5@jar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- com.google.auto.service:auto-service:1.1.1@jar
+--- com.google.auto:auto-common:1.2.1@jar
+--- com.google.guava:guava:32.0.1-jre@jar
+--- com.google.errorprone:error_prone_annotations:2.18.0@jar
+--- androidx.constraintlayout:constraintlayout-core:1.0.4@jar
+--- org.pgpainless:sop-java:7.0.0@jar
+--- com.google.code.findbugs:jsr305:3.0.2@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.auto.service:auto-service-annotations:1.1.1@jar
+--- org.bouncycastle:bcpg-jdk18on:1.76@jar
+--- org.bouncycastle:bcprov-jdk18on:1.76@jar
+--- com.google.guava:failureaccess:1.0.1@jar
+--- org.checkerframework:checker-qual:3.33.0@jar
\--- com.google.j2objc:j2objc-annotations:2.8@jar

releaseUnitTest
releaseUnitTestCompileClasspath - Dependencies for compilation
+--- :app (variant: release)
+--- ch.acra:acra-core:5.11.2@aar
+--- com.google.android.material:material:1.11.0@aar
+--- androidx.appcompat:appcompat:1.6.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.activity:activity:1.8.0@aar
+--- androidx.work:work-runtime-ktx:2.7.1@aar
+--- androidx.work:work-runtime:2.7.1@aar
+--- androidx.dynamicanimation:dynamicanimation:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.lifecycle:lifecycle-livedata-core:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2@aar
+--- androidx.core:core-ktx:1.12.0@aar
+--- androidx.appcompat:appcompat-resources:1.6.1@aar
+--- androidx.drawerlayout:drawerlayout:1.1.1@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.customview:customview:1.1.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.6.2@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.6.2@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10@jar
+--- androidx.constraintlayout:constraintlayout:2.1.4@aar
+--- org.slf4j:slf4j-api:2.0.9@jar
+--- com.github.tony19:logback-android:3.0.0@aar
+--- net.lingala.zip4j:zip4j:2.11.5@jar
+--- org.pgpainless:pgpainless-sop:1.6.2@jar
+--- com.google.code.gson:gson:2.10.1@jar
+--- junit:junit:4.13.2@jar
+--- org.hamcrest:hamcrest-core:1.3@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10@jar
+--- androidx.savedstate:savedstate:1.2.1@aar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.cardview:cardview:1.0.0@aar
+--- androidx.versionedparcelable:versionedparcelable:1.1.1@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-common:2.2.0@jar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- androidx.startup:startup-runtime:1.1.1@aar
+--- androidx.resourceinspection:resourceinspection-annotation:1.0.1@jar
\--- org.pgpainless:sop-java:7.0.0@jar

releaseUnitTestRuntimeClasspath - Dependencies for runtime/packaging
+--- junit:junit:4.13.2@jar
+--- ch.acra:acra-core:5.11.2@aar
+--- com.google.android.material:material:1.11.0@aar
+--- androidx.constraintlayout:constraintlayout:2.1.4@aar
+--- androidx.appcompat:appcompat-resources:1.6.1@aar
+--- androidx.appcompat:appcompat:1.6.1@aar
+--- androidx.viewpager2:viewpager2:1.0.0@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.fragment:fragment:1.3.6@aar
+--- androidx.activity:activity:1.8.0@aar
+--- androidx.emoji2:emoji2-views-helper:1.2.0@aar
+--- androidx.emoji2:emoji2:1.2.0@aar
+--- androidx.savedstate:savedstate:1.2.1@aar
+--- androidx.work:work-runtime-ktx:2.7.1@aar
+--- androidx.work:work-runtime:2.7.1@aar
+--- androidx.dynamicanimation:dynamicanimation:1.0.0@aar
+--- androidx.legacy:legacy-support-core-utils:1.0.0@aar
+--- androidx.loader:loader:1.0.0@aar
+--- androidx.lifecycle:lifecycle-service:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-livedata:2.6.2@aar
+--- androidx.lifecycle:lifecycle-common:2.6.2@jar
+--- androidx.lifecycle:lifecycle-livedata-core:2.6.2@aar
+--- androidx.lifecycle:lifecycle-process:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel:2.6.2@aar
+--- androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2@aar
+--- androidx.core:core-ktx:1.12.0@aar
+--- androidx.drawerlayout:drawerlayout:1.1.1@aar
+--- androidx.coordinatorlayout:coordinatorlayout:1.1.0@aar
+--- androidx.transition:transition:1.2.0@aar
+--- androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
+--- androidx.vectordrawable:vectordrawable:1.1.0@aar
+--- androidx.viewpager:viewpager:1.0.0@aar
+--- androidx.recyclerview:recyclerview:1.1.0@aar
+--- androidx.customview:customview:1.1.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.core:core:1.12.0@aar
+--- androidx.lifecycle:lifecycle-runtime:2.6.2@aar
+--- androidx.lifecycle:lifecycle-runtime-ktx:2.6.2@aar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4@jar
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10@jar
+--- org.pgpainless:pgpainless-sop:1.6.2@jar
+--- org.pgpainless:pgpainless-core:1.6.2@jar
+--- org.slf4j:slf4j-api:2.0.9@jar
+--- com.github.tony19:logback-android:3.0.0@aar
+--- net.lingala.zip4j:zip4j:2.11.5@jar
+--- com.google.code.gson:gson:2.10.1@jar
+--- org.hamcrest:hamcrest-core:1.3@jar
+--- androidx.annotation:annotation-experimental:1.3.0@aar
+--- androidx.cursoradapter:cursoradapter:1.0.0@aar
+--- androidx.resourceinspection:resourceinspection-annotation:1.0.1@jar
+--- androidx.cardview:cardview:1.0.0@aar
+--- androidx.interpolator:interpolator:1.0.0@aar
+--- androidx.versionedparcelable:versionedparcelable:1.1.1@aar
+--- androidx.collection:collection:1.1.0@jar
+--- androidx.room:room-runtime:2.2.5@aar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-runtime:2.2.0@aar
+--- androidx.arch.core:core-common:2.2.0@jar
+--- androidx.profileinstaller:profileinstaller:1.3.0@aar
+--- androidx.startup:startup-runtime:1.1.1@aar
+--- androidx.tracing:tracing:1.0.0@aar
+--- androidx.sqlite:sqlite-framework:2.1.0@aar
+--- androidx.sqlite:sqlite:2.1.0@aar
+--- androidx.concurrent:concurrent-futures:1.1.0@jar
+--- androidx.documentfile:documentfile:1.0.0@aar
+--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar
+--- androidx.print:print:1.0.0@aar
+--- androidx.room:room-common:2.2.5@jar
+--- androidx.annotation:annotation-jvm:1.6.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10@jar
+--- com.google.auto.service:auto-service:1.1.1@jar
+--- com.google.auto:auto-common:1.2.1@jar
+--- com.google.guava:guava:32.0.1-jre@jar
+--- com.google.errorprone:error_prone_annotations:2.18.0@jar
+--- androidx.constraintlayout:constraintlayout-core:1.0.4@jar
+--- org.pgpainless:sop-java:7.0.0@jar
+--- com.google.code.findbugs:jsr305:3.0.2@jar
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10@jar
+--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar
+--- org.jetbrains:annotations:13.0@jar
+--- com.google.auto.service:auto-service-annotations:1.1.1@jar
+--- org.bouncycastle:bcpg-jdk18on:1.76@jar
+--- org.bouncycastle:bcprov-jdk18on:1.76@jar
+--- com.google.guava:failureaccess:1.0.1@jar
+--- org.checkerframework:checker-qual:3.33.0@jar
\--- com.google.j2objc:j2objc-annotations:2.8@jar
DependencyReportTask has been deprecated and will be removed in AGP 9.0
*/
